### ISSUE TITLE
`extract` command error when `--collection` parameter is missing: BSON field 'listCollections.include_system_collections' is an unknown field

### ISSUE THREAD

**Issue by karynzv** [crate/mongodb-cratedb-migration-tool#5]
Even though the documentation states you can use the extract command without specifying the `collection`, when running the following command:
`migr8 extract --host localhost --port 27017 --database test`

I got the following error:
```Traceback (most recent call last):
  File ".../migr8", line 8, in <module>
    sys.exit(main())
  File ".../migr8/__main__.py", line 223, in main
    extract_to_file(args)
  File ".../migr8/__main__.py", line 110, in extract_to_file
    schema = extract(args)
  File ".../migr8/__main__.py", line 162, in extract
    filtered_collections = gather_collections(db)
  File ".../migr8/__main__.py", line 122, in gather_collections
    collections = database.list_collection_names(include_system_collections=False)
  File ".../pymongo/database.py", line 856, in list_collection_names
    for result in self.list_collections(session=session, **kwargs)]
  File ".../pymongo/database.py", line 818, in list_collections
    return self.__client._retryable_read(
  File ".../pymongo/mongo_client.py", line 1464, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File ".../pymongo/database.py", line 814, in _cmd
    return self._list_collections(
  File ".../pymongo/database.py", line 763, in _list_collections
    cursor = self._command(
  File ".../pymongo/database.py", line 619, in _command
    return sock_info.command(
  File ".../pymongo/pool.py", line 603, in command
    return command(self.sock, dbname, spec, slave_ok,
  File ".../pymongo/network.py", line 165, in command
    helpers._check_command_response(
  File ".../pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: BSON field 'listCollections.include_system_collections' is an unknown field.
```

However, if I specify the collection as in:
`migr8 extract --host localhost --port 27017 --database test --collection movies`
It works as intended

**Comment by amotl** [comment]
Maybe related?

- https://github.com/mongodb/mongo-python-driver/pull/177
- https://github.com/mongodb/mongo-python-driver/pull/401
- https://github.com/mongomock/mongomock/issues/736

**Comment by amotl** [comment]
When running on a recent MongoDB server, we may need to update to a more recent version of the Python driver. That is, pymongo 4.

- https://pypi.org/project/pymongo/

Currently, the program uses pymongo 3.

https://github.com/crate/mongodb-cratedb-migration-tool/blob/e90e6f05bf01ed151862003ed2d57eb1869223d3/setup.py#L37

**Comment by amotl** [comment]
Can you try to omit the `include_system_collections` argument here, and/or check if it has been renamed?
```python
  File ".../migr8/__main__.py", line 122, in gather_collections
    collections = database.list_collection_names(include_system_collections=False)
```

**Comment by amotl** [comment]
Hi Karyn,

> When running on a recent MongoDB server [...]

Indeed: By using GH-6, we have been able to reproduce the error you are reporting, when using MongoDB 5.

```
docker run -it --rm --publish=27017:27017 mongo:5
python -m unittest -vvv -k test_gather_collections
```

```
pymongo.errors.OperationFailure: BSON field 'listCollections.include_system_collections' is an unknown field., full error: {'ok': 0.0, 'errmsg': "BSON field 'listCollections.include_system_collections' is an unknown field.", 'code': 40415, 'codeName': 'Location40415'}
```
Edit: Now also demonstrated at [CI run #18145710037](https://github.com/crate/mongodb-cratedb-migration-tool/actions/runs/6676551905/job/18145710037?pr=6#step:6:72)

When using MongoDB 4, it works.
```
docker run -it --rm --publish=27017:27017 mongo:4
python -m unittest -vvv -k test_gather_collections
```
```
Ran 1 test in 0.013s
```

I think the issue will be easily resolved by just updating `pymongo`, which should accompany for any changes there.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

those two patches will improve the situation about supporting MongoDB >= 5 more properly.

- GH-6
- GH-8

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi Karyn,

version 0.3.0 has been released, including those updates referenced above. Can I ask you to report back if that resolves the issue you reported?

With kind regards,
Andreas.

-- https://github.com/crate/mongodb-cratedb-migration-tool/releases/tag/0.3.0

**Comment by amotl** [comment]
Considering this as resolved. Please re-open when applicable. Thank you again.
